### ISSUE TITLE
Vuejs having issue importing parseURL

### ISSUE THREAD

**Issue by ieow** [solana-labs/solana-pay#66] opened 2022-02-09 07:00 UTC
```
Uncaught TypeError: fields must be array of Layout instances
    at new Structure (webpack-internal:///./node_modules/@solana/pay/node_modules/@solana/buffer-layout/lib/Layout.js:1183:13)
    at exports.struct (webpack-internal:///./node_modules/@solana/pay/node_modules/@solana/buffer-layout/lib/Layout.js:2862:56)
    at eval (webpack-internal:///./node_modules/@solana/pay/node_modules/@solana/spl-token/lib/esm/instructions/initializeMint.mjs:23:100)
    at Module../node_modules/@solana/pay/node_modules/@solana/spl-token/lib/esm/instructions/initializeMint.mjs (chunk-vendors.js:4148:1)
    at __webpack_require__ (app.js:315:33)
    at fn (app.js:617:21)
    at eval (webpack-internal:///./node_modules/@solana/pay/node_modules/@solana/spl-token/lib/esm/instructions/index.mjs:94:77)
    at Module../node_modules/@solana/pay/node_modules/@solana/spl-token/lib/esm/instructions/index.mjs (chunk-vendors.js:4102:1)
    at __webpack_require__ (app.js:315:33)
    at fn (app.js:617:21)
 
```
Hit error above when try to add the example code in vue example project

```
const testparse = async () =>{
  const url =
    'solana:mvines9iiHiQTysrwkJjGf2gb9Ex9jXJX8ns3qwf2kN?amount=0.01&reference=82ZJ7nbGpixjeDCmEhUcmwXYfvurzAgGdtSMuHnUgyny&label=Michael&message=Thanks%20for%20all%20the%20fish&memo=OrderId5678';
  const { recipient, amount, splToken, reference, label, message, memo } = parseURL(url);

}
```

using packages below

```
  "dependencies": {
    "@solana/pay": "^0.1.1",
    "@solana/spl-token": "^0.1.8",
    "@solana/web3.js": "^1.31.0",
    "bs58": "^4.0.1",
    "core-js": "^3.8.3",
    "tweetnacl": "^1.0.3",
    "vue": "^3.2.6"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "@vue/cli-plugin-babel": "~5.0.0-beta.4",
    "@vue/cli-plugin-eslint": "~5.0.0-beta.4",
    "@vue/cli-plugin-typescript": "~5.0.0-beta.4",
    "@vue/cli-service": "~5.0.0-beta.4",
    "@vue/compiler-sfc": "^3.2.6",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^7.20.0",
    "eslint-plugin-vue": "^7.2.0",
    "stream-browserify": "^3.0.0",
    "typescript": "~4.1.5"
  }
 ```

**Comment by ieow** [comment] 2022-02-09 07:18
Tested with vitejs example vue project (which use rollup)
still hit (TypeError) error below

```
Uncaught TypeError: fields must be array of Layout instances
    at new Structure (:3000/node_modules/.vite/@solana_pay.js?v=259bbafe:3664:17)
    at exports.struct (:3000/node_modules/.vite/@solana_pay.js?v=259bbafe:4320:60)
    at :3000/node_modules/.vite/@solana_pay.js?v=259bbafe:32117:70
```

**Comment by ieow** [comment] 2022-02-10 04:34
It works fine with vitejs - react-ts

**Comment by jordansexton** [comment] 2022-02-10 05:36
Hmm, I can't say what the issue is. But if it works with Vite and React, the issue isn't with the library, so I'll close this for now. If you figure it out, please follow up!

**Closed by jordansexton** 2022-02-10 05:36 UTC

**Comment by ieow** [comment] 2022-02-10 09:56
I hit this issue on my M1 Mac machine. 
Tested on my linux machine. It works fine for vue.
Not sure why
