### ISSUE TITLE
[todo] Document how to deploy app to Vercel / Netlify

### ISSUE THREAD

**Issue by walter-grace** [solana-labs/solana-pay#46] opened 2022-02-02 20:14 UTC
Is there a way to run build and deploy it to netlify or vercel just for demo purposes?

**Comment by jordansexton** [comment] 2022-02-02 22:46
Yes! The [point of sale app](https://github.com/solana-labs/solana-pay/tree/master/point-of-sale) is set up as a Vercel app. It can be deployed to Vercel for anyone to run their own instance with minimal config. I think we should document those steps though.

**Comment by walter-grace** [comment] 2022-02-02 23:55
> Yes! The [point of sale app](https://github.com/solana-labs/solana-pay/tree/master/point-of-sale) is set up as a Vercel app. It can be deployed to Vercel for anyone to run their own instance with minimal config. I think we should document those steps though.

Yes please! I have designed a front end and would like to deploy it for a prototype. Documentation for such would be awesome

**Comment by jordansexton** [comment] 2022-02-03 03:26
These are the settings you want to set up Vercel with:

<img width="733" alt="vercel_1" src="https://user-images.githubusercontent.com/1173161/152276322-8fdb9fa3-005f-4f25-94db-18e445bceebd.png">

<img width="728" alt="vercel_2" src="https://user-images.githubusercontent.com/1173161/152276325-11e9910b-ee9e-4b1b-af27-593a5037c349.png">

We should integrate these into the docs soon. @cogoo @benmills or anyone who wants to PR is welcome!

**Comment by walter-grace** [comment] 2022-02-03 04:32
<img width="561" alt="Screen Shot 2022-02-02 at 8 27 58 PM" src="https://user-images.githubusercontent.com/31444892/152281529-f5c854fc-fb62-4594-b272-f22e9f5cb0ec.png">
I get a build error when trying to deploy from a fork- Am I missing something?

**Comment by jordansexton** [comment] 2022-02-03 04:36
Given that I can't see your build error, I can't really say :)

**Comment by walter-grace** [comment] 2022-02-03 04:37
<img width="511" alt="Screen Shot 2022-02-02 at 8 36 37 PM" src="https://user-images.githubusercontent.com/31444892/152281896-bae93f33-7dbc-4a2a-9254-f79eb4ca16b6.png">
Sorry forgot this part :) @jordansexton

**Comment by jordansexton** [comment] 2022-02-03 04:42
Ah that's probably https://github.com/solana-labs/solana-pay/issues/44

There's a workaround, which is to install the buffer and stream-browserify packages it wants.

This will get fixed tomorrow though.

**Comment by walter-grace** [comment] 2022-02-03 05:09
> Ah that's probably #44
> 
> There's a workaround, which is to install the buffer and stream-browserify packages it wants.
> 
> This will get fixed tomorrow though.

Thank you! Cant wait to get it up and running

**Comment by jordansexton** [comment] 2022-02-03 20:46
This should be fixed! See https://github.com/solana-labs/solana-pay/issues/44#issuecomment-1029385302

Please pull the latest and try again!

**Comment by walter-grace** [comment] 2022-02-03 22:44
<img width="205" alt="Screen Shot 2022-02-03 at 2 44 00 PM" src="https://user-images.githubusercontent.com/31444892/152441718-e5f02ece-8b65-4b9b-bd4d-02350f0f7cc9.png">
Still running into what seems a build issue. I just forked the repo and tried to build on vercel. Do I need to do anything before that?

**Comment by jordansexton** [comment] 2022-02-03 23:35
I'm seeing the same thing. It's definitely a bug, sorry about that! Working on root cause.

**Comment by jordansexton** [comment] 2022-02-04 01:37
Okay, I found a fix for this. Publishing and deploying now.

**Comment by jordansexton** [comment] 2022-02-04 02:21
I believe this should be fixed now via https://github.com/solana-labs/solana-pay/pull/54

Please pull the latest and try to deploy again! I just did and it worked.

**Comment by walter-grace** [comment] 2022-02-04 02:39
All seems to be working now! Closing the issue-

**Comment by jordansexton** [comment] 2022-02-04 02:51
Ah, I'll reopen until we actually document this!

**Closed** 2022-02-05 20:40 UTC
Labels: enhancement
